apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: micro-bot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: micro-bot
    spec:
      containers:
        - name: bot
          env:
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-token
                  key: SLACK_TOKEN
          resources:
            limits:
              cpu: "10m"
          command: [
          "/micro",
          "--registry_address=http://svc-consul.default.svc.cluster.local:8500",
          "--register_ttl=60",
          "--register_interval=30",
          "--selector=cache",
          "bot",
          "--inputs=slack",
          "--slack_token=$SLACK_TOKEN"
          ]
          image: microhq/micro:bot
          imagePullPolicy: Always
